<a href="https://colab.research.google.com/github/lakshit2808/Machine-Learning-Notes/blob/master/Deep_Learning/ANN/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

An artificial neural network (ANN) is the piece of a computing system designed to simulate the way the human brain analyzes and processes information. 


<img src='https://github.com/lakshit2808/Machine-Learning-Notes/blob/master/Deep_Learning/ANN/Stochastic_Gradient_Descent.png?raw=true'/>

**Read About Stochastic Gradient Decent [Here](https://en.wikipedia.org/wiki/Stochastic_gradient_descent)

### Importing the libraries

In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [37]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [38]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [40]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [42]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [84]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [85]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

`Units` are no. of neurons, `activation` is for activation function we are using rectifier function as an activation function

Read More about Activation Function [Here](https://en.wikipedia.org/wiki/Activation_function)

### Adding the second hidden layer

In [86]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu'))

### Adding the output layer

In [87]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) ## Using Sigmoid Function as an Activation Function

## Part 3 - Training the ANN

### Compiling the ANN

In [88]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [89]:
ann.fit(X_train, y_train, batch_size=64, epochs = 100)

Epoch 1/100
125/125 [==============================] - 1s 1ms/step - loss: 0.6513 - accuracy: 0.6271
Epoch 2/100
125/125 [==============================] - 0s 1ms/step - loss: 0.5244 - accuracy: 0.7914
Epoch 3/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4718 - accuracy: 0.7993
Epoch 4/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4470 - accuracy: 0.7997
Epoch 5/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4355 - accuracy: 0.8026
Epoch 6/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4299 - accuracy: 0.8055
Epoch 7/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4261 - accuracy: 0.8060
Epoch 8/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4230 - accuracy: 0.8083
Epoch 9/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8092
Epoch 10/100
125/125 [==============================] - 0s 1ms/step - loss: 0.4184 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [90]:
result = ann.predict(sc.transform([[1, 0, 0, 500, 1, 40, 3, 20000, 2, 1, 1, 50000]])) > 0.5
result[0][0]

False

### Predicting the Test set results

In [91]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [92]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 189  216]]


0.8625