<a href="https://colab.research.google.com/github/lakshit2808/Machine-Learning-Notes/blob/master/Pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Pandas</h1>
Pandas is a opensource python library prividing high performance data manuplation and analysis tools using it's powerful data structures.


In [2]:
import pandas as pd
import numpy as np

<h2>Series</h2>
Series is a single dimensional data structure with homogenous data type values.<br>
Also Series comes with index or are one single column where as list is just a list

In [3]:
series = pd.Series([10,20,40,50], index = ["a" , "b","c", "d"])
lists = [1,2,3]
print(lists)
series



[1, 2, 3]


a    10
b    20
c    40
d    50
dtype: int64

<h1>Dataframe</h1>
Two dimensional object with heterogenous data type value.

In [4]:
listz = [['Ravi' , 10],['Ram' , 20],["Raj", 30]]
print(listz)

df = pd.DataFrame(listz, columns=['Name', "Age"], index=["a", "b", 'c'])
df

[['Ravi', 10], ['Ram', 20], ['Raj', 30]]


Name  Age
a  Ravi   10
b   Ram   20
c   Raj   30

<h2>Accessing DataFrame</h2>

In [5]:
dfa = df['Name']
dfb = df[['Name']]
print(type(dfa))
print(type(dfb))
dfa

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


a    Ravi
b     Ram
c     Raj
Name: Name, dtype: object

dfa is a series because we are directly accessing column values, whereas dfb is a DataFrame because we are accessing a total column

<h2>Dictionary to DataFrame</h2>

In [6]:
dictz = {"Name": ["Rahul", 'Rio'], "Age" : [20,40]}
print(dictz)

dfd = pd.DataFrame(dictz)
dfd

{'Name': ['Rahul', 'Rio'], 'Age': [20, 40]}


Name  Age
0  Rahul   20
1    Rio   40

## Array to DataFrame

In [7]:
arr = np.array([[1,2,3] , [5,6,7]])
print(arr)

dfa = pd.DataFrame(arr)
print(dfa)

## Now dataframe into array
arrd = np.array(dfa)
arrd

[[1 2 3]
 [5 6 7]]
   0  1  2
0  1  2  3
1  5  6  7


array([[1, 2, 3],
       [5, 6, 7]])

## Range Data

Syntax: pd.date_range(date, period , freq)<br>
date format: YYYYMMDD<br>
period: it is the no of days or months or years<br>
frequency(freq): it is the format i.e Month(M), Year(Y), Day(D)

In [8]:
from datetime import datetime

ranges = pd.date_range(start=datetime.now(), periods=10, freq='Y')
type(ranges)
ranges

DatetimeIndex(['2021-12-31 02:17:33.718836', '2022-12-31 02:17:33.718836',
               '2023-12-31 02:17:33.718836', '2024-12-31 02:17:33.718836',
               '2025-12-31 02:17:33.718836', '2026-12-31 02:17:33.718836',
               '2027-12-31 02:17:33.718836', '2028-12-31 02:17:33.718836',
               '2029-12-31 02:17:33.718836', '2030-12-31 02:17:33.718836'],
              dtype='datetime64[ns]', freq='A-DEC')

## Head Tail Func
- pd.head() # Returns the first 5 values and to change these 5 values we can pass n in pd.head(3) it will return first 3 values.
- pd.tail() # Returns the last 5 values and to change these 5 values we can pass n in pd.tail(3) it will return last 3 values.

In [9]:
# Create Df
df = np.random.randn(10,4)
print(df)
df = pd.DataFrame(df , index = ranges, columns = ["Random 1", "Random 2", "Random 3", "Random 4"])
print(df)
print(df.shape)
print(df.columns)
print(df.info())
print(df.head(3))
print("#####")
print(df.tail(3))

[[ 0.11528778  0.42575385  0.50889499 -0.85651488]
 [-0.31236161  1.71018002 -0.33406335 -1.0882227 ]
 [ 0.81421087 -0.10738301 -0.868758   -0.07373167]
 [ 0.36156357  1.18266918  0.75924142  1.42412196]
 [ 1.4461178  -1.1896709  -0.46957543 -0.30733707]
 [-0.07129229 -0.51919864  0.08044894 -0.57642001]
 [-0.82925325 -1.26239156  0.71410825 -0.2072894 ]
 [-0.55172686  0.95065898 -1.00006963  0.22046126]
 [-1.30354255  0.17156924 -0.92659867  0.47130744]
 [-1.73130868  0.41436142 -0.05935615 -1.07586915]]
                            Random 1  Random 2  Random 3  Random 4
2021-12-31 02:17:33.718836  0.115288  0.425754  0.508895 -0.856515
2022-12-31 02:17:33.718836 -0.312362  1.710180 -0.334063 -1.088223
2023-12-31 02:17:33.718836  0.814211 -0.107383 -0.868758 -0.073732
2024-12-31 02:17:33.718836  0.361564  1.182669  0.759241  1.424122
2025-12-31 02:17:33.718836  1.446118 -1.189671 -0.469575 -0.307337
2026-12-31 02:17:33.718836 -0.071292 -0.519199  0.080449 -0.576420
2027-12-31 02:17:33.

## Null values

In [10]:
print(df.isnull()) # null values are there or not
print(df.isnull().sum()) # sum of null values in each column
df.dropna() # by default it'll delete the entire row there nan value is present but to delete the column we can use df.dropna(axis=1) by default axis is 0

                            Random 1  Random 2  Random 3  Random 4
2021-12-31 02:17:33.718836     False     False     False     False
2022-12-31 02:17:33.718836     False     False     False     False
2023-12-31 02:17:33.718836     False     False     False     False
2024-12-31 02:17:33.718836     False     False     False     False
2025-12-31 02:17:33.718836     False     False     False     False
2026-12-31 02:17:33.718836     False     False     False     False
2027-12-31 02:17:33.718836     False     False     False     False
2028-12-31 02:17:33.718836     False     False     False     False
2029-12-31 02:17:33.718836     False     False     False     False
2030-12-31 02:17:33.718836     False     False     False     False
Random 1    0
Random 2    0
Random 3    0
Random 4    0
dtype: int64


Random 1  Random 2  Random 3  Random 4
2021-12-31 02:17:33.718836  0.115288  0.425754  0.508895 -0.856515
2022-12-31 02:17:33.718836 -0.312362  1.710180 -0.334063 -1.088223
2023-12-31 02:17:33.718836  0.814211 -0.107383 -0.868758 -0.073732
2024-12-31 02:17:33.718836  0.361564  1.182669  0.759241  1.424122
2025-12-31 02:17:33.718836  1.446118 -1.189671 -0.469575 -0.307337
2026-12-31 02:17:33.718836 -0.071292 -0.519199  0.080449 -0.576420
2027-12-31 02:17:33.718836 -0.829253 -1.262392  0.714108 -0.207289
2028-12-31 02:17:33.718836 -0.551727  0.950659 -1.000070  0.220461
2029-12-31 02:17:33.718836 -1.303543  0.171569 -0.926599  0.471307
2030-12-31 02:17:33.718836 -1.731309  0.414361 -0.059356 -1.075869

## Values

In [11]:
print(df.value_counts()) # it'll return the no. of occurence of the data

df.dtypes # >> to know each datatype

# Same for column
print(df['Random 1'].value_counts())
print(df.corr()) # to find the relation between adjusent column

Random 1   Random 2   Random 3   Random 4 
 1.446118  -1.189671  -0.469575  -0.307337    1
 0.814211  -0.107383  -0.868758  -0.073732    1
 0.361564   1.182669   0.759241   1.424122    1
 0.115288   0.425754   0.508895  -0.856515    1
-0.071292  -0.519199   0.080449  -0.576420    1
-0.312362   1.710180  -0.334063  -1.088223    1
-0.551727   0.950659  -1.000070   0.220461    1
-0.829253  -1.262392   0.714108  -0.207289    1
-1.303543   0.171569  -0.926599   0.471307    1
-1.731309   0.414361  -0.059356  -1.075869    1
dtype: int64
 0.814211    1
-0.551727    1
-0.829253    1
-0.312362    1
 0.361564    1
-1.731309    1
-0.071292    1
-1.303543    1
 0.115288    1
 1.446118    1
Name: Random 1, dtype: int64
          Random 1  Random 2  Random 3  Random 4
Random 1  1.000000 -0.223284 -0.002333  0.173973
Random 2 -0.223284  1.000000 -0.101611  0.088740
Random 3 -0.002333 -0.101611  1.000000  0.021206
Random 4  0.173973  0.088740  0.021206  1.000000


In [12]:
df.describe() ## Gives the summary of the columnwise data

Random 1   Random 2   Random 3   Random 4
count  10.000000  10.000000  10.000000  10.000000
mean   -0.206231   0.177655  -0.159573  -0.206949
std     0.958255   0.976616   0.670514   0.776104
min    -1.731309  -1.262392  -1.000070  -1.088223
25%    -0.759872  -0.416245  -0.768962  -0.786491
50%    -0.191827   0.292965  -0.196710  -0.257313
75%     0.299995   0.819433   0.401783   0.146913
max     1.446118   1.710180   0.759241   1.424122

## Slicing

In [13]:
df[0:2]

Random 1  Random 2  Random 3  Random 4
2021-12-31 02:17:33.718836  0.115288  0.425754  0.508895 -0.856515
2022-12-31 02:17:33.718836 -0.312362  1.710180 -0.334063 -1.088223

### loc vs iloc
- loc is used to access data by putting the location for the data. i.e `df.loc["2021-12-31 01:49:18.893933", "Random 1"][0]`
  - In the first block he have inserted the row value and in second block we have inserted the column value.
- iloc is used to access data using the index. i.e `df.iloc[[0,2,5],0:2]`

In [15]:
df.loc["2021-12-31", "Random 1"]

2021-12-31 02:17:33.718836    0.115288
Freq: A-DEC, Name: Random 1, dtype: float64

In [ ]:
df.iloc[[0,2,5],-1]

In [ ]:
print(df)
df.iloc[[2,4,6], 0:2]

## Concatenation & Descriptive Statistics
- `df.drop()`:- mainly used to delete columns

In [ ]:
drd = df.drop(columns=["Random 1", "Random 2"])

- `df.concat()`:- It is used to merge to dataframes row wise

In [ ]:

a = {"Name": ["Rio", "Nirobi"], "Age" :[18,20]}
a = pd.DataFrame(a)

b = {"Name": ["Tokyo", "Berlin", "Tokyo"], "Age" :[23,30,23]}
b = pd.DataFrame(b, index= [2,3,4])

ab = pd.concat([a,b])
ab

- Knowing the existance of value.

In [ ]:
print(ab["Name"] == "Tokyo", '\n\n') ## tells the existance

print(ab[ab["Name"] == "Tokyo"]) ## Shows the existance

- Deleting the dublicate `df.drop_duplicates(column_name)`
  - it'll delete the whole row.


In [ ]:
ab = ab.drop_duplicates(['Name'])

- Sorting values `df.sort_values(column_name)` it can sort numerically as well alphabatically.



In [ ]:
ab_sort_aplha = ab.sort_values('Name')

- renaming columns `df.rename(columns = {"Name": "Emp_name"})`

In [ ]:
ab_sort_aplha.rename(columns={"Name":"Emp_Name" , "Age": "Emp_Age"})

- Other functions
  - `df.sum()` to find the sum of values
  - `df.mean()` to find the mean of values
  - `df.median()` to find the median of the values
  -`df.mode()` to find the mode of the values
  - `df.std()` to find the standard deviation of the values
  - `df.min()` to find the minimum value from the all values
  - `df.max()` to find the maximum value from the all values

- `pd.merge` Merges df column wise, here `on="Name"` means we are looking for Name in both the df.

In [40]:
di1 = {"Name":["Rahul" , "Sham" , "Ram"], "Age": [12,23,45]}
df1 = pd.DataFrame(di1)

di2 = {"Course": ["Machine Learning", "Data Science" , 'MLops'], 'Name': ["Rahul" , "Sham" , "Ram"], "Year":[2020,2017,2015]}
df2 = pd.DataFrame(di2)

df = pd.merge(df1, df2 , on='Name', how="inner" )
df

Name  Age            Course  Year
0  Rahul   12  Machine Learning  2020
1   Sham   23      Data Science  2017
2    Ram   45             MLops  2015

In [33]:
## Doing changes in df
df.rename(columns={"Name": "Student_Name"})
df.iloc[0,0] = 'Virat'
df

Name  Age            Course  Year
0  Virat   12  Machine Learning  2020
1   Sham   23      Data Science  2017
2    Ram   45             MLops  2015

## Data Cleaning

In [61]:
dfs = pd.Series(['Lakshit', '18', 'www.lakshit.io'])
dfs.str.capitalize()

dfs.str.islower()
dfs.str.lower()

dfs.str.isupper()
dfs.str.upper()

dfs.str.isnumeric()

dfs.str.swapcase()

dfs.str.len()

dfs.str.cat(sep="_") # >> Lakshit_18_www.lakshit.io

dfs.str.replace("www." , "yoyo.")

dfs.str.repeat(2)

dfs.str.count("w") # occurence of a letter

0    0
1    0
2    3
dtype: int64

## Applying funtions to tables
- `df.pipe(func_name)` it'll apply to the whole table.
- `df.apply(func_name)` it'll apply to each column.

In [70]:
num = np.random.rand(10,4)
dfNum = pd.DataFrame(num)
print(dfNum,'\n\n')

def add(a,b):
  return a + b

dfNum.pipe(type) # >> pandas.core.frame.DataFrame

# PIPE
print(dfNum.pipe(add,10), '\n\n')

# Apply
dfNum.apply(np.mean)

          0         1         2         3
0  0.003335  0.654678  0.538664  0.248774
1  0.213139  0.480437  0.563553  0.306054
2  0.395779  0.361534  0.954765  0.935977
3  0.465944  0.394300  0.036275  0.088152
4  0.603514  0.915837  0.368850  0.443080
5  0.045305  0.681098  0.877889  0.395374
6  0.848147  0.094486  0.036311  0.024125
7  0.477000  0.193999  0.005057  0.898425
8  0.349697  0.687879  0.119028  0.770602
9  0.071841  0.643406  0.905111  0.105964 


           0          1          2          3
0  10.003335  10.654678  10.538664  10.248774
1  10.213139  10.480437  10.563553  10.306054
2  10.395779  10.361534  10.954765  10.935977
3  10.465944  10.394300  10.036275  10.088152
4  10.603514  10.915837  10.368850  10.443080
5  10.045305  10.681098  10.877889  10.395374
6  10.848147  10.094486  10.036311  10.024125
7  10.477000  10.193999  10.005057  10.898425
8  10.349697  10.687879  10.119028  10.770602
9  10.071841  10.643406  10.905111  10.105964 




0    0.347370
1    0.510765
2    0.440550
3    0.421653
dtype: float64

In [75]:
import os
os.getcwd() # to get the current working directiory
# os.chdir("dir_name") # to change the current working directiory


'/content'

In [78]:
df.dtypes

Name      object
Age        int64
Course    object
Year       int64
dtype: object

## Importing csv file

In [103]:
df = pd.read_csv("sample_data/california_housing_test.csv" ,header=0, skiprows=[1,2,3,4,5],\
                 names = ['Long', 'Lat', "house_med_age", 'Rooms', 'bedrooms','population_','household', "med_inc","med_val"])


- here header = 0 is by default you can change header toany other row by putting the row number.
- here skiprows will skip the rows which are specified 
- here names is used to give custom header name
- put `header = None` to remove header 

In [104]:
df

Long    Lat  house_med_age  ...  household  med_inc   med_val
0    -119.56  36.51           37.0  ...      204.0   1.6635   67000.0
1    -121.43  38.63           43.0  ...      218.0   1.6641   67000.0
2    -120.65  35.48           19.0  ...      441.0   3.2250  166900.0
3    -122.84  38.40           15.0  ...      599.0   3.6696  194400.0
4    -118.02  34.08           31.0  ...      603.0   2.3333  164200.0
...      ...    ...            ...  ...        ...      ...       ...
2990 -119.86  34.42           23.0  ...      607.0   1.1790  225000.0
2991 -118.14  34.06           27.0  ...     1036.0   3.3906  237200.0
2992 -119.70  36.30           10.0  ...      220.0   2.2895   62000.0
2993 -117.12  34.10           40.0  ...       14.0   3.2708  162500.0
2994 -119.63  34.42           42.0  ...      260.0   8.5608  500001.0

[2995 rows x 9 columns]

In [112]:
df = pd.read_csv("sample_data/california_housing_test.csv", header= None, prefix="Column: ", na_values=["na value"], verbose=True)


Tokenization took: 1.56 ms
Type conversion took: 6.00 ms
Parser memory cleanup took: 0.01 ms


- here `prefix = "column: "` is used to add any prefix to the column names i.e Column: 1
- `na_values=['na_value']` is used to fill replace the na value with na_value  
- We can also use `sep=";"` if the seperator is not ',' we have to specify the seperator
- `dtype={"Column: 0": 'int'}` if you want to change the data type of a column then specify it here.
- `verbose=True` is used to get the time it takes to load the file

In [111]:
print(df)
df.dtypes

        Column: 0  Column: 1  ...      Column: 7           Column: 8
0       longitude   latitude  ...  median_income  median_house_value
1     -122.050000  37.370000  ...       6.608500       344700.000000
2     -118.300000  34.260000  ...       3.599000       176500.000000
3     -117.810000  33.780000  ...       5.793400       270500.000000
4     -118.360000  33.820000  ...       6.135900       330000.000000
...           ...        ...  ...            ...                 ...
2996  -119.860000  34.420000  ...       1.179000       225000.000000
2997  -118.140000  34.060000  ...       3.390600       237200.000000
2998  -119.700000  36.300000  ...       2.289500        62000.000000
2999  -117.120000  34.100000  ...       3.270800       162500.000000
3000  -119.630000  34.420000  ...       8.560800       500001.000000

[3001 rows x 9 columns]


Column: 0    object
Column: 1    object
Column: 2    object
Column: 3    object
Column: 4    object
Column: 5    object
Column: 6    object
Column: 7    object
Column: 8    object
dtype: object