<a href="https://colab.research.google.com/github/lakshit2808/Machine-Learning-Notes/blob/master/pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Pandas</h1>
Pandas is a opensource python library prividing high performance data manuplation and analysis tools using it's powerful data structures.


In [2]:
import pandas as pd
import numpy as np

<h2>Series</h2>
Series is a single dimensional data structure with homogenous data type values.<br>
Also Series comes with index or are one single column where as list is just a list

In [3]:
series = pd.Series([10,20,40,50], index = ["a" , "b","c", "d"])
lists = [1,2,3]
print(lists)
series



[1, 2, 3]


a    10
b    20
c    40
d    50
dtype: int64

<h1>Dataframe</h1>
Two dimensional object with heterogenous data type value.

In [4]:
listz = [['Ravi' , 10],['Ram' , 20],["Raj", 30]]
print(listz)

df = pd.DataFrame(listz, columns=['Name', "Age"], index=["a", "b", 'c'])
df

[['Ravi', 10], ['Ram', 20], ['Raj', 30]]


Name  Age
a  Ravi   10
b   Ram   20
c   Raj   30

<h2>Accessing DataFrame</h2>

In [5]:
dfa = df['Name']
dfb = df[['Name']]
print(type(dfa))
print(type(dfb))
dfa

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


a    Ravi
b     Ram
c     Raj
Name: Name, dtype: object

dfa is a series because we are directly accessing column values, whereas dfb is a DataFrame because we are accessing a total column

<h2>Dictionary to DataFrame</h2>

In [6]:
dictz = {"Name": ["Rahul", 'Rio'], "Age" : [20,40]}
print(dictz)

dfd = pd.DataFrame(dictz)
dfd

{'Name': ['Rahul', 'Rio'], 'Age': [20, 40]}


Name  Age
0  Rahul   20
1    Rio   40

## Array to DataFrame

In [7]:
arr = np.array([[1,2,3] , [5,6,7]])
print(arr)

dfa = pd.DataFrame(arr)
print(dfa)

## Now dataframe into array
arrd = np.array(dfa)
arrd

[[1 2 3]
 [5 6 7]]
   0  1  2
0  1  2  3
1  5  6  7


array([[1, 2, 3],
       [5, 6, 7]])

## Range Data

Syntax: pd.date_range(date, period , freq)<br>
date format: YYYYMMDD<br>
period: it is the no of days or months or years<br>
frequency(freq): it is the format i.e Month(M), Year(Y), Day(D)

In [8]:
from datetime import datetime

ranges = pd.date_range(start=datetime.now(), periods=10, freq='Y')
type(ranges)
ranges

DatetimeIndex(['2021-12-31 01:49:18.893933', '2022-12-31 01:49:18.893933',
               '2023-12-31 01:49:18.893933', '2024-12-31 01:49:18.893933',
               '2025-12-31 01:49:18.893933', '2026-12-31 01:49:18.893933',
               '2027-12-31 01:49:18.893933', '2028-12-31 01:49:18.893933',
               '2029-12-31 01:49:18.893933', '2030-12-31 01:49:18.893933'],
              dtype='datetime64[ns]', freq='A-DEC')

## Head Tail Func
- pd.head() # Returns the first 5 values and to change these 5 values we can pass n in pd.head(3) it will return first 3 values.
- pd.tail() # Returns the last 5 values and to change these 5 values we can pass n in pd.tail(3) it will return last 3 values.

In [9]:
# Create Df
df = np.random.randn(10,4)
print(df)
df = pd.DataFrame(df , index = ranges, columns = ["Random 1", "Random 2", "Random 3", "Random 4"])
print(df)
print(df.shape)
print(df.columns)
print(df.info())
print(df.head(3))
print("#####")
print(df.tail(3))

[[-1.38298131  0.02404788  1.35825343 -0.745622  ]
 [ 1.41350605 -0.88746797  0.68184189 -0.38715781]
 [-0.25249418 -1.11714603  0.21687026  1.14296467]
 [-1.14513523  0.61876946 -0.92652884 -0.63957972]
 [ 0.67305248  1.19992034 -0.85272386 -0.23429196]
 [-0.1819319   2.13948672  0.27335711  1.90863015]
 [ 1.34613787 -0.34223781 -0.50346852  1.41693512]
 [-0.00693004 -0.20604805 -0.63220105  0.79379967]
 [-0.17920824  1.13177641 -1.09948005  0.51391719]
 [ 0.25235028 -0.6322879   0.8690657   0.60613505]]
                            Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933 -1.382981  0.024048  1.358253 -0.745622
2022-12-31 01:49:18.893933  1.413506 -0.887468  0.681842 -0.387158
2023-12-31 01:49:18.893933 -0.252494 -1.117146  0.216870  1.142965
2024-12-31 01:49:18.893933 -1.145135  0.618769 -0.926529 -0.639580
2025-12-31 01:49:18.893933  0.673052  1.199920 -0.852724 -0.234292
2026-12-31 01:49:18.893933 -0.181932  2.139487  0.273357  1.908630
2027-12-31 01:49:18.

## Null values

In [10]:
print(df.isnull()) # null values are there or not
print(df.isnull().sum()) # sum of null values in each column
df.dropna() # by default it'll delete the entire row there nan value is present but to delete the column we can use df.dropna(axis=1) by default axis is 0

                            Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933     False     False     False     False
2022-12-31 01:49:18.893933     False     False     False     False
2023-12-31 01:49:18.893933     False     False     False     False
2024-12-31 01:49:18.893933     False     False     False     False
2025-12-31 01:49:18.893933     False     False     False     False
2026-12-31 01:49:18.893933     False     False     False     False
2027-12-31 01:49:18.893933     False     False     False     False
2028-12-31 01:49:18.893933     False     False     False     False
2029-12-31 01:49:18.893933     False     False     False     False
2030-12-31 01:49:18.893933     False     False     False     False
Random 1    0
Random 2    0
Random 3    0
Random 4    0
dtype: int64


Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933 -1.382981  0.024048  1.358253 -0.745622
2022-12-31 01:49:18.893933  1.413506 -0.887468  0.681842 -0.387158
2023-12-31 01:49:18.893933 -0.252494 -1.117146  0.216870  1.142965
2024-12-31 01:49:18.893933 -1.145135  0.618769 -0.926529 -0.639580
2025-12-31 01:49:18.893933  0.673052  1.199920 -0.852724 -0.234292
2026-12-31 01:49:18.893933 -0.181932  2.139487  0.273357  1.908630
2027-12-31 01:49:18.893933  1.346138 -0.342238 -0.503469  1.416935
2028-12-31 01:49:18.893933 -0.006930 -0.206048 -0.632201  0.793800
2029-12-31 01:49:18.893933 -0.179208  1.131776 -1.099480  0.513917
2030-12-31 01:49:18.893933  0.252350 -0.632288  0.869066  0.606135

## Values

In [11]:
print(df.value_counts()) # it'll return the no. of occurence of the data

# Same for column
print(df['Random 1'].value_counts())
print(df.corr()) # to find the relation between adjusent column

Random 1   Random 2   Random 3   Random 4 
 1.413506  -0.887468   0.681842  -0.387158    1
 1.346138  -0.342238  -0.503469   1.416935    1
 0.673052   1.199920  -0.852724  -0.234292    1
 0.252350  -0.632288   0.869066   0.606135    1
-0.006930  -0.206048  -0.632201   0.793800    1
-0.179208   1.131776  -1.099480   0.513917    1
-0.181932   2.139487   0.273357   1.908630    1
-0.252494  -1.117146   0.216870   1.142965    1
-1.145135   0.618769  -0.926529  -0.639580    1
-1.382981   0.024048   1.358253  -0.745622    1
dtype: int64
 0.252350    1
 1.346138    1
 0.673052    1
-0.006930    1
-1.382981    1
-0.181932    1
-1.145135    1
-0.179208    1
 1.413506    1
-0.252494    1
Name: Random 1, dtype: int64
          Random 1  Random 2  Random 3  Random 4
Random 1  1.000000 -0.255130 -0.106428  0.284438
Random 2 -0.255130  1.000000 -0.395773  0.134978
Random 3 -0.106428 -0.395773  1.000000 -0.099569
Random 4  0.284438  0.134978 -0.099569  1.000000


In [12]:
df.describe() ## Gives the summary of the columnwise data

Random 1   Random 2   Random 3   Random 4
count  10.000000  10.000000  10.000000  10.000000
mean    0.053637   0.192881  -0.061501   0.437573
std     0.922014   1.049049   0.856127   0.911267
min    -1.382981  -1.117146  -1.099480  -0.745622
25%    -0.234854  -0.559775  -0.797593  -0.348941
50%    -0.093069  -0.091000  -0.143299   0.560026
75%     0.567877   1.003525   0.579721   1.055673
max     1.413506   2.139487   1.358253   1.908630

## Slicing

In [15]:
df[0:2]

Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933 -1.382981  0.024048  1.358253 -0.745622
2022-12-31 01:49:18.893933  1.413506 -0.887468  0.681842 -0.387158

### loc vs iloc
- loc is used to access data by putting the location for the data. i.e `df.loc["2021-12-31 01:49:18.893933", "Random 1"][0]`
  - In the first block he have inserted the row value and in second block we have inserted the column value.
- iloc is used to access data using the index. i.e `df.iloc[[0,2,5],0:2]`

In [44]:
df.loc["2021-12-31 01:49:18.893933", "Random 1":]

Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933 -1.382981  0.024048  1.358253 -0.745622

In [46]:
df.iloc[[0,2,5],-1]

2021-12-31 01:49:18.893933   -0.745622
2023-12-31 01:49:18.893933    1.142965
2026-12-31 01:49:18.893933    1.908630
Name: Random 4, dtype: float64

In [49]:
print(df)
df.iloc[[2,4,6], 0:2]

                            Random 1  Random 2  Random 3  Random 4
2021-12-31 01:49:18.893933 -1.382981  0.024048  1.358253 -0.745622
2022-12-31 01:49:18.893933  1.413506 -0.887468  0.681842 -0.387158
2023-12-31 01:49:18.893933 -0.252494 -1.117146  0.216870  1.142965
2024-12-31 01:49:18.893933 -1.145135  0.618769 -0.926529 -0.639580
2025-12-31 01:49:18.893933  0.673052  1.199920 -0.852724 -0.234292
2026-12-31 01:49:18.893933 -0.181932  2.139487  0.273357  1.908630
2027-12-31 01:49:18.893933  1.346138 -0.342238 -0.503469  1.416935
2028-12-31 01:49:18.893933 -0.006930 -0.206048 -0.632201  0.793800
2029-12-31 01:49:18.893933 -0.179208  1.131776 -1.099480  0.513917
2030-12-31 01:49:18.893933  0.252350 -0.632288  0.869066  0.606135


Random 1  Random 2
2023-12-31 01:49:18.893933 -0.252494 -1.117146
2025-12-31 01:49:18.893933  0.673052  1.199920
2027-12-31 01:49:18.893933  1.346138 -0.342238

## Concatenation & Descriptive Statistics
- `df.drop()`:- mainly used to delete columns

In [55]:
drd = df.drop(columns=["Random 1", "Random 2"])

- `df.concat()`:- It is used to merge to dataframes

In [66]:

a = {"Name": ["Rio", "Nirobi"], "Age" :[18,20]}
a = pd.DataFrame(a)

b = {"Name": ["Tokyo", "Berlin", "Tokyo"], "Age" :[23,30,23]}
b = pd.DataFrame(b, index= [2,3,4])

ab = pd.concat([a,b])
ab

Name  Age
0     Rio   18
1  Nirobi   20
2   Tokyo   23
3  Berlin   30
4   Tokyo   23

- Knowing the existance of value.

In [71]:
print(ab["Name"] == "Tokyo", '\n\n') ## tells the existance

print(ab[ab["Name"] == "Tokyo"]) ## Shows the existance

0    False
1    False
2     True
3    False
4     True
Name: Name, dtype: bool 


    Name  Age
2  Tokyo   23
4  Tokyo   23


- Deleting the dublicate `df.drop_duplicates(column_name)`
  - it'll delete the whole row.


In [76]:
ab = ab.drop_duplicates(['Name'])

- Sorting values `df.sort_values(column_name)` it can sort numerically as well alphabatically.



In [80]:
ab_sort_aplha = ab.sort_values('Name')

- renameing columns `df.rename(columns = {"Name": "Emp_name"})`

In [83]:
ab_sort_aplha.rename(columns={"Name":"Emp_Name" , "Age": "Emp_Age"})

Emp_Name  Emp_Age
3   Berlin       30
1   Nirobi       20
0      Rio       18
2    Tokyo       23

- Other functions
  - `df.sum()` to find the sum of values
  - `df.mean()` to find the mean of values
  - `df.median()` to find the median of the values
  -`df.mode()` to find the mode of the values
  - `df.std()` to find the standard deviation of the values
  - `df.min()` to find the minimum value from the all values
  - `df.max()` to find the maximum value from the all values