<a href="https://colab.research.google.com/github/lakshit2808/Machine-Learning-Notes/blob/master/Data_Preprocessing/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing
Data preprocessing is a data mining technique that involves transforming raw data into understandable format.

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Importing the dataset
`x` is feature dataset and `y` is dependent variable

In [22]:
df = pd.read_csv('/Data.csv')

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [24]:
print(type(x))
x

<class 'numpy.ndarray'>


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [25]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [31]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable
`ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder ='passthrough')`<br>
Note:- it will return the vector.
So,In the following line we have passed a tuple to `transformers` with the value count of 3 the first one is `'encode'` which is the type of task, the second one is `OneHotEncoder()` encoding will be done with this class, and the last one is index i.e `[0]` where we want to do the encoding. <br>
The other parameter which is passed to `ColumnTransformer()` is `remainder` which is used to pass away the other columns then Country. 

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))


In [38]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable
Note:- It'll return the `0` and `1` value

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [39]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [40]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)

In [41]:
print(x_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [42]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [55]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [56]:
print(y_test)

[0 1]


## Feature Scaling
Feature scaling is a method used to normalize the range of independent variables or features of data.

- Normalisation
  - scales the range to [0, 1] or sometimes [-1, 1]
  - Formula
    - X_new = (X - X_min)/(X_max - X_min)
- Standardisation
  - It is not bounded to a certain range
  - Formula
    - X_new = (X - mean)/Std

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [64]:
print(x_train)

[[1.0 0.0 0.0 1.2909944487358058 -0.1915918438457855 -1.0781259408412427]
 [1.0 0.0 1.0 -0.7745966692414834 -0.014117293757057819
  -0.07013167641635415]
 [0.0 1.0 0.0 -0.7745966692414834 0.5667085065333239 0.6335624327104546]
 [1.0 0.0 0.0 1.2909944487358058 -0.30453019390224867 -0.307866172742979]
 [1.0 0.0 0.0 1.2909944487358058 -1.901801144700799 -1.4204636155515822]
 [0.0 1.0 0.0 -0.7745966692414834 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 1.0 -0.7745966692414834 1.4379472069688966 1.5749910381638883]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7401495441200352 -0.5646194287757336]]


In [65]:
print(x_test)

[[1.0 0.0 1.0 -0.7745966692414834 -1.4661817944830127 -0.9069571034860731]
 [0.0 1.0 0.0 -0.7745966692414834 -0.44973664397484414
  0.20564033932253015]]
