<a href="https://colab.research.google.com/github/lakshit2808/Machine-Learning-Notes/blob/master/Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- It is a library to build multidimensional array

## Numpy VS List
- Numpy is much Faster than List
- It uses less memory than list
- No data type checking
- It uses contiguous memory where as list don't uses it
- One can't do arithmetic operations directly on two or more list but it can be done on array. E.g Array1 * Array2 = New_Array

## What can we do with numpy?
- Insertion, Deletion, apending, concatnating, and lot more(Just wait for this notebook to end)

## Application of Numpy:
- Mathematics, It's a great alternative to MATLAB
- Plotting
- Backend for Pandas, Digital Photographs, Connect4
- Machine Learning

## Installation 
`pip install numpy` or `pip3 install numpy` for Mac and Linux
<hr>

## Basics

In [133]:
import numpy as np

- 1-D Array

In [ ]:
a = np.array([1,2,4,5])
a

array([1, 2, 4, 5])

- 2-D Array

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- 3-D Array

In [ ]:
c = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]],[[7,8,9],[9,8,7]]])
c

array([[[1, 2, 3],
        [3, 2, 1]],

       [[4, 5, 6],
        [6, 5, 4]],

       [[7, 8, 9],
        [9, 8, 7]]])

- Get Dimensions of Array

In [ ]:
print(a.ndim)
print(b.ndim)

1
2


- Get Shape of Array

In [ ]:
print(a.shape)
print(b.shape)

(4,)
(2, 4)


- Knowing the Datatype

In [ ]:
print(a.dtype)
print(b.dtype)

int64
int64


- Knowing the memory size
- `a.itemsize` returns the size of each element of array
- `a.nbytes` returns the size of complete array

In [ ]:
print(a.itemsize)
print(a.nbytes)

8
32


## Accessing, Changing specific row, column, and element

In [173]:
a = np.array([[3,4,5,5,8,2],[1,2,3,4,5,6]])
print(a, '\n')
## Accessing Element
print(a[1][2])

## Accessing Row
print(a[1])

## Accessing Column
print(a[ : , 2], '\n')

## Accessing a particular value
print(a[0][[0,3]])

[[3 4 5 5 8 2]
 [1 2 3 4 5 6]] 

3
[1 2 3 4 5 6]
[5 3] 

[3 5]


In [ ]:
## Changing Element
a[0,1] = 10
print(a,'\n')

## Changing Row
a[0] = [6,5,3,4,7,2]
print(a,'\n')

## Changing Column
a[:, 0] = [2,3]
print(a)

[[ 3 10  5  5  8  2]
 [ 1  2  3  4  5  6]] 

[[6 5 3 4 7 2]
 [1 2 3 4 5 6]] 

[[2 5 3 4 7 2]
 [3 2 3 4 5 6]]


- Accessing Changing in 3-D Array

In [ ]:
print(c,"\n\n")

## Accessing Element
print(c[1,0,2])

## Accessing Row
print(c[2,0])

## Accessing Column
print(c[1,:,1])

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [9 8 7]]] 


6
[7 8 9]
[5 5]


In [ ]:
## Changing Element
c[0,0,2] = 100
print(c,'\n\n\n')

## Changing Row
c[1,0,:] = [10,20,30]
print(c,'\n\n\n')

## Changing Column
c[2,:,1] = [3,3]
print(c,'\n\n\n')

[[[  1   2 100]
  [  3   2   1]]

 [[  4   5   6]
  [  6   5   4]]

 [[  7   8   9]
  [  9   8   7]]] 



[[[  1   2 100]
  [  3   2   1]]

 [[ 10  20  30]
  [  6   5   4]]

 [[  7   8   9]
  [  9   8   7]]] 



[[[  1   2 100]
  [  3   2   1]]

 [[ 10  20  30]
  [  6   5   4]]

 [[  7   3   9]
  [  9   3   7]]] 





## Initalize Different Types of Array
- All 0s Matrix
  - Here `(2,2)` tells the dimensions of the matrix

In [ ]:
d1 = np.zeros((2,2))
d1

array([[0., 0.],
       [0., 0.]])

- All 1s Matrix
  - You may also specify the datatype too `dtype = '**float32**'`

In [ ]:
d2 = np.ones((2,3), dtype='int32')
d2

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

- Custom number Matrix
  - Here `20` is custom number

In [ ]:
d2 = np.full((3,3), 20, dtype='float32')
d2

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]], dtype=float32)

- `np.full_like` helps to make an array with dimensions same as any other array but with a custom number.

In [ ]:
d3 = np.full_like(d2, 30)
d3

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]], dtype=float32)

- Random Array
  - Here `(3,3)` are the dimensions
  - `random_sample(d3.shape)` will give a random array but with the dimesions like d3

In [ ]:
d4 = np.random.rand(3,3)
print(d4,'\n\n')

d5 = np.random.random_sample(d3.shape)
print(d5)


[[0.12422939 0.13516935 0.26879838]
 [0.43506147 0.47416247 0.12029659]
 [0.05069875 0.25953858 0.68642061]] 


[[0.38263749 0.81382741 0.21135767]
 [0.83932947 0.27577764 0.89337746]
 [0.42996201 0.24341893 0.61485042]]


- Random Integer Array
  - Here `12,14` is the range of data and `size=(3,3)` are the dimesions, If you put `14` only and remove `12` it'll take a default range of 0 to 14

In [ ]:
d6 = np.random.randint(12,14, size=(2,3))
d6

array([[12, 13, 12],
       [13, 13, 12]])

- Identity Matrix

In [ ]:
d7 = np.identity(3)
d7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- Repeating an Array
  - Here `d6` is the array for repeating, `3` is the number of times one wants to repeat it, `axis = 0` is an optional parameter to represent the array in vertical form. 

In [ ]:
d8 = np.repeat(d6,3, axis =0)
d8

array([[12, 13, 12],
       [12, 13, 12],
       [12, 13, 12],
       [13, 13, 12],
       [13, 13, 12],
       [13, 13, 12]])

- Merging two Arrays

In [ ]:
a = np.random.randint(10, size=(3,3))
print(a,'\n\n')

b = np.zeros((2,2))
print(b,'\n\n')

a[1:, 0:2] = b
a

[[8 2 2]
 [9 7 5]
 [5 9 3]] 


[[0. 0.]
 [0. 0.]] 




array([[8, 2, 2],
       [0, 0, 5],
       [0, 0, 3]])

- Copying Array

In [ ]:
b = a.copy()
b

array([[8, 2, 2],
       [0, 0, 5],
       [0, 0, 3]])

## Mathematics with Numpy
- Arthematic with constant

In [ ]:
arr = np.full((2,2), 5)

- Addition

In [ ]:
arr + 2

array([[7, 7],
       [7, 7]])

- Subtraction

In [ ]:
arr-2

array([[3, 3],
       [3, 3]])

- Multiplication

In [ ]:
arr*2

array([[10, 10],
       [10, 10]])

- Divide

In [ ]:
arr / 5

array([[1., 1.],
       [1., 1.]])

- Remender

In [ ]:
arr%2

array([[1, 1],
       [1, 1]])

- Power

In [ ]:
arr**2

array([[25, 25],
       [25, 25]])

- Trignometry
  - Same for cos, tan, and all
  - **For Maths** More at https://numpy.org/doc/stable/reference/routines.math.html
  - **For Linear Algebra** More at https://numpy.org/doc/stable/reference/routines.linalg.html
  - **For Statistics** More at https://numpy.org/doc/stable/reference/routines.statistics.html?highlight=statistics

In [135]:
np.sin(arr)

array([[-0.95892427, -0.95892427],
       [-0.95892427, -0.95892427]])

- Arthematic between two arrays
  - Note: Dimension of both array must be same for the operation to happen

In [147]:
a = np.full((2,2),9)
b = np.full((2,2),3)

## Addition
print(a + b, '\n\n')

## Subtraction
print(a - b, '\n\n')

## Multiplication
print(a * b, '\n\n')

## Divide
print(a / b, '\n\n')

## Remender
print(a % b, '\n\n')

## Power
print(a ** b, '\n\n')

[[12 12]
 [12 12]] 


[[6 6]
 [6 6]] 


[[27 27]
 [27 27]] 


[[3. 3.]
 [3. 3.]] 


[[0 0]
 [0 0]] 


[[729 729]
 [729 729]] 




## Reorganizing Array

- Reshape

In [152]:
arr = np.random.randint(10, size=(3,3))
arr.reshape(1,9)

array([[4, 8, 7, 3, 0, 6, 7, 4, 3]])

- Vertical Stacking vectors

In [157]:
arr1 = np.ones((1,5))
arr2 = np.zeros((1,5))

arr = np.vstack((arr1,arr2))
arr


array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

- Hosizontal Stacking Vector

In [158]:
arr1 = np.ones((1,5))
arr2 = np.zeros((1,5))

arr = np.hstack((arr1,arr2))
arr

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

## Loading Data from File
- Here `delimiter`  is the sign which is used to seperate data in the file
- `astype` is used to convert the datatype

In [162]:
data = np.genfromtxt('/content/sample_data/california_housing_test.csv', delimiter=',')
data = data.astype('int32')
data

array([[-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [       -122,          37,          27, ...,         606,
                  6,      344700],
       [       -118,          34,          43, ...,         277,
                  3,      176500],
       ...,
       [       -119,          36,          10, ...,         220,
                  2,       62000],
       [       -117,          34,          40, ...,          14,
                  3,      162500],
       [       -119,          34,          42, ...,         260,
                  8,      500001]], dtype=int32)

## Boolean Masking and Advance Indexing

In [164]:
data > 50

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       ...,
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ...,  True, False,  True]])

In [167]:
data[data > 50]

array([  3885,    661,   1537, ...,    753,    260, 500001], dtype=int32)

- `np.any` checks if in column/row any of the value is greater then a given number, `axis=1` for row


In [175]:
np.any(data > 50,axis =0)

array([False, False,  True,  True,  True,  True,  True, False,  True])

- `np.all` checks if all the values in column/row is greater then a given number 

In [176]:
np.all(data > 50,axis =0)

array([False, False, False, False, False, False, False, False, False])

- If data between 50 ad 100 exists or not

In [178]:
((data > 50) & (data < 100))

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

- Not between 50 and 100

In [180]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])